# Generated by Django 5.2.2 on 2025-06-26 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('original_year', models.IntegerField(blank=True, null=True)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ratings_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookEdition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=13, null=True)),
                ('language_code', models.CharField(blank=True, max_length=10, null=True)),
                ('ratings_count', models.PositiveIntegerField()),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='bookrating.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrating.author')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrating.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='authors',
            field=models.ManyToManyField(related_name='works', through='bookrating.WorkAuthor', to='bookrating.author'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookrating.bookedition')),
            ],
            options={
                'unique_together': {('user_id', 'edition')},
            },
        ),
        migrations.AddConstraint(
            model_name='workauthor',
            constraint=models.UniqueConstraint(fields=('work', 'author'), name='unique_work_author'),
        ),
    ]
