# Generated by Django 5.2.2 on 2025-06-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedition',
            name='num_pages',
        ),
        migrations.RemoveField(
            model_name='bookedition',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='bookedition',
            name='publisher',
        ),
    ]
