# Generated by Django 5.2.2 on 2025-06-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrating', '0002_remove_bookedition_num_pages_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workauthor',
            constraint=models.UniqueConstraint(fields=('work', 'author'), name='unique_work_author'),
        ),
    ]
