# Generated by Django 5.2.2 on 2025-06-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrating', '0003_workauthor_unique_work_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='authors',
            field=models.ManyToManyField(related_name='works', through='bookrating.WorkAuthor', to='bookrating.author'),
        ),
    ]
