# Generated by Django 5.2.2 on 2025-06-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrating', '0004_alter_work_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditionTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
